# Site settings
email: matheus.andrade.dev@gmail.com
baseurl: "/blog-lib" # the subpath of your site, e.g. /blog/
url: "http://math-s.github.io" # the base hostname & protocol for your site
twitter_username: silva_math_
github_username:  math-s

# Build settings
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-coffeescript
  - "jekyll-github-metadata"
sass:
  sass_dir: _sass
  style: compressed