title:
  - Matheus Andrade
description:
  - A short description of your site's purpose
email: matheus.andrade.dev@gmail.com
baseurl: /blog-lib
url: http://math-s.github.io
twitter_username: silva_math_
github_username: math-s
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-coffeescript
  - jekyll-github-metadata
  - jekyll-sass-converter
  - jekyll-remote-theme
sass:
  sass_dir: _sass
  style: compressed